# Generated by Django 6.0.1 on 2026-01-07 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Groceries, Electronics)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive categories won't show in product listings")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='System-generated unique order number', max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total order value in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('emi_count', models.IntegerField(default=4, help_text='Number of EMI installments (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='pending', help_text='Current order status', max_length=15)),
                ('order_date', models.DateField(auto_now_add=True, help_text='Date when order was placed')),
                ('due_date', models.DateField(blank=True, help_text='Final payment due date (order_date + 30 days)', null=True)),
                ('approval_date', models.DateField(blank=True, help_text='Date when wholesaler approved the order', null=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Date when order was delivered', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any special instructions or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_owner', models.ForeignKey(help_text='Shop owner who placed this order', limit_choices_to={'role': 'shop_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_placed', to=settings.AUTH_USER_MODEL)),
                ('wholesaler', models.ForeignKey(help_text='Wholesaler fulfilling this order', limit_choices_to={'role': 'wholesaler'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='Installment number (1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid in this installment', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField(help_text='Due date for this installment')),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this installment has been paid')),
                ('paid_date', models.DateField(blank=True, help_text='Date when payment was received', null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount received', max_digits=12)),
                ('is_late', models.BooleanField(default=False, help_text='True if payment was made after due date')),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference (UPI ID, cheque number, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='The order this EMI belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='emi_schedules', to='core.order')),
            ],
            options={
                'verbose_name': 'EMI Schedule',
                'verbose_name_plural': 'EMI Schedules',
                'ordering': ['order', 'installment_number'],
                'unique_together': {('order', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Debit to Account)'), ('debit', 'Debit (Payment Received)')], help_text='Type of transaction', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(help_text='Transaction description', max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance after this transaction', max_digits=12)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User whose credit is affected', on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('emi', models.ForeignKey(blank=True, help_text='Related EMI schedule (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.emischedule')),
                ('order', models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.order')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name as displayed to customers', max_length=200)),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique identifier (e.g., PROD-001)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available quantity in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_quantity', models.IntegerField(default=1, help_text='Minimum quantity that can be ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, help_text='Product image for catalog display', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive products won't appear in catalog")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category')),
                ('wholesaler', models.ForeignKey(help_text='Wholesaler managing this product', limit_choices_to={'role': 'wholesaler'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name (stored for historical reference)', max_length=200)),
                ('quantity', models.IntegerField(help_text='Number of units ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price for this line item', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(help_text='Product being ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this daily record')),
                ('total_orders', models.IntegerField(default=0, help_text='Number of orders placed on this day')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sales value for the day', max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payments received on this day', max_digits=12)),
                ('new_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='New credit taken on this day', max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance at end of day', max_digits=12)),
                ('on_time_payments', models.IntegerField(default=0, help_text='Number of on-time payments')),
                ('late_payments', models.IntegerField(default=0, help_text='Number of late payments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Shop owner this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Sales',
                'verbose_name_plural': 'Daily Sales',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
