# Generated by Django 6.0.1 on 2026-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (if not uploading)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image for catalog display (upload)', null=True, upload_to='products/'),
        ),
    ]
