# Generated by Django 6.0.1 on 2026-01-07 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLimitSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_limit', models.DecimalField(decimal_places=2, help_text='ML-suggested credit limit in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current assigned credit limit', max_digits=12)),
                ('limit_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference: suggested - current', max_digits=12)),
                ('feature_data', models.JSONField(default=dict, help_text='Features used for this suggestion')),
                ('model_version', models.CharField(help_text='Version of the ML model used', max_length=50)),
                ('confidence_score', models.FloatField(default=0.8, help_text="Model's confidence in this suggestion", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this suggestion was approved')),
                ('approved_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Actual approved limit (may differ from suggestion)', max_digits=12, null=True)),
                ('suggestion_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True, help_text='True if this is the latest suggestion')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Wholesaler who approved this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Shop owner being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='credit_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Limit Suggestion',
                'verbose_name_plural': 'Credit Limit Suggestions',
                'ordering': ['-suggestion_date'],
            },
        ),
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('risk', 'Default Risk (Random Forest)'), ('credit_limit', 'Credit Limit (Linear Regression)'), ('segmentation', 'Shop Segmentation (K-Means)')], help_text='Type of ML model', max_length=20)),
                ('version', models.CharField(help_text='Model version (e.g., v1.0.0)', max_length=50)),
                ('file_path', models.CharField(help_text='Path to the saved .pkl file', max_length=255)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('training_samples', models.IntegerField(help_text='Number of samples used for training')),
                ('accuracy_score', models.FloatField(help_text='Performance metric (depends on model type)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metrics', models.JSONField(default=dict, help_text='Additional performance metrics')),
                ('features_used', models.JSONField(default=list, help_text='List of features used for training')),
                ('hyperparameters', models.JSONField(default=dict, help_text='Model hyperparameters')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the currently active model')),
                ('notes', models.TextField(blank=True, help_text='Notes about this model version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ML Model Metadata',
                'verbose_name_plural': 'ML Model Metadata',
                'ordering': ['-training_date'],
                'unique_together': {('model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_probability', models.FloatField(help_text='Probability of default (0.0 = no risk, 1.0 = certain default)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_category', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], help_text='Risk category derived from probability', max_length=10)),
                ('feature_data', models.JSONField(default=dict, help_text='Snapshot of features used for this prediction')),
                ('model_version', models.CharField(help_text='Version of the ML model used (e.g., rf_v1.0)', max_length=50)),
                ('confidence_score', models.FloatField(default=0.8, help_text="Model's confidence in this prediction", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True, help_text='True if this is the latest prediction for this user')),
                ('user', models.ForeignKey(help_text='Shop owner being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Prediction',
                'verbose_name_plural': 'Risk Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(help_text='Cluster number (0, 1, 2, ...)')),
                ('cluster_name', models.CharField(help_text='Human-readable segment name', max_length=100)),
                ('cluster_description', models.TextField(blank=True, help_text="Description of this segment's characteristics")),
                ('distance_to_center', models.FloatField(help_text='Distance from cluster center (lower = better fit)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('feature_data', models.JSONField(default=dict, help_text='Features used for clustering')),
                ('cluster_center', models.JSONField(default=dict, help_text='Cluster center values (mean of all features)')),
                ('model_version', models.CharField(help_text='Version of the K-Means model', max_length=50)),
                ('segmentation_date', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True, help_text='True if this is the latest segmentation')),
                ('user', models.ForeignKey(help_text='Shop owner being segmented', on_delete=django.db.models.deletion.CASCADE, related_name='shop_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Segment',
                'verbose_name_plural': 'Shop Segments',
                'ordering': ['-segmentation_date'],
            },
        ),
    ]
